### PR TITLE
extracting the import code into function and using flags

### PR DESCRIPTION
**Pull request by oren**

### CODE REVIEW

**Comment by oren** [comment]
@robertmeta, I am not sure where should I draw the boundary between the `Storage` struct and the rest of the code. For example, should the `importPokemon` function also be part of the Storage? 
Also, should this function take care of inserting the slice into the db?

Maybe adding the first test will make the design more clear (dependency injection etc).

**Comment by robertmeta** [comment]
Remember -- the goal of this code is being good for a talk, single files work better.  Also, add structure as the project demands, and not before, great example of this is https://www.youtube.com/watch?v=eIWFnNz8mF4 (notice how he pulls code out of low value separate files into main file).

**Comment by oren** [comment]
ok. so maybe i don't even need a struct. i can `AddQuad` inside each iteration of `scanner.Scan`.

**Comment by oren** [comment]
does that looks better? is it a good time to write a test and maybe have the reading part on a separate go file?

**Pull request merged**
